/**:
  ros__parameters:
    debug: true
    target_frame: odom_vision
    max_armor_distance: 10.0

    ekf:
      sigma2_q_x: 10.0
      sigma2_q_y: 10.0

      sigma2_q_z: 1.0

      sigma2_q_yaw: 20.0
      sigma2_q_r: 80.0


     # r_x: 0.10288572347
      #r_y: 0.1064594022
      #r_z: 0.250901387
      #r_yaw: 0.0144229309

      r_x: 0.0846537194
      r_y: 0.1521677530
      r_z: 0.1083228776
      r_yaw: 0.1332647596








    tracker:
      max_match_distance: 2.0
      max_match_yaw_diff: 0.7

      tracking_thres: 2
      lost_time_thres: 1.0
    
    solver:
      prediction_delay: 0.015
      controller_delay: 0.025
      max_tracking_v_yaw: 1.5 #转速(rad/s)大于这个值时瞄准机器人中心 
      side_angle: 25.375
      bullet_speed: 20.5                                                            
      compenstator_type: "ideal" #ideal或resistance
      gravity: 9.8
      resistance: 0.021
      iteration_times: 120 # 补偿的迭代次数s
