/**:
  ros__parameters:
    camera_info_url: package://rm_bringup/config/camera_info.yaml
    exposure_time: 1500
    gain: 8.0
    resolution_width: 1440
    resolution_height: 1080
    offsetX: 0
    offsetY: 0
    camera_name: "daheng"
    recording: false    #是否录制
