odom2camera:
  xyz: "\"0.12249  0.0  0.0381\""
  rpy: "\"0.0  -0.005 0.02\""

#p小了向上偏，y大了往左偏WWW


# 设置启动参数
# 命名空间 所有节点、话题都会以这个命名空间开头，如/some_namespace/image_raw
namespace: ''
# true: 读取视频 false: 读取相机
video_play: false 
# true: 虚拟下位机 false: 实车 
virtual_serial: false 
# true: 开启打符 false：关闭打符W
rune: true 
# true: 启动导航tf false：不启动导航tf
navigation: false
